### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by oboroccv** [sizifart/MMProBumpBot#1]
PS C:\BOT\BUMP> python main.py
Traceback (most recent call last):
  File "C:\BOT\BUMP\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\BOT\BUMP\bot\utils\__init__.py", line 7, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments
PS C:\BOT\BUMP>

**Comment by SilentWarrior1** [comment]
i have an error either, but in some different way: i just cant get an api_hash -->telegram says ERROR every time i'm trying to create new app. (tried MANY different ip's/browsers.
can you pls make a script with different auth way? (query_id, or smth like it?)
